version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
    - MYSQL_ROOT_PASSWORD=mailtrain
    - MYSQL_DATABASE=mailtrain
    - MYSQL_USER=mailtrain
    - MYSQL_PASSWORD=mailtrain
    volumes:
    - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    deploy:
      resources:
          limits:
            cpus: "0.5"
            memory: "500M"

  redis:
    image: redis:7
    volumes:
    - redis-data:/data
    ports:
      - 6379:6379
    deploy:
      resources:
          limits:
            cpus: "0.5"
            memory: "1G"

  mongo:
    image: mongo:6
    volumes:
    - mongo-data:/data/db
    ports:
      - 27017:27017
    deploy:
      resources:
          limits:
            cpus: "0.5"
            memory: "1G"

volumes:
  mysql-data:
  redis-data:
  mongo-data:

