#Minimal Dockerfile for hot workaround v20260416.2
#docker buildx build --platform linux/arm64,linux/amd64 . -f Dockerfile.mini --tag highcanfly/hcfmailer-plus:v20260416.3 --push   
FROM highcanfly/hcfmailer-plus:v20260416.2

COPY --from=ismogroup/busybox:latest /busybox-1.37.0/busybox /usr/sbin/busybox
RUN chmod +x /usr/sbin/busybox && ln -sf /usr/sbin/busybox /usr/sbin/sendmail

RUN apt-get update && apt-get install -y --no-install-recommends \
    pwgen netcat-openbsd imagemagick curl xz-utils file cron && \
    rm -rf /var/lib/apt/lists/* && \
    echo "23       20      *       *       0       /app/scripts/autobackup" > /etc/cron.d/autobackup && \
    echo "23       43      *       *       *       /app/scripts/autobackup-s3" > /etc/cron.d/autobackup-s3 && \
    echo "*/10     *       *       *       *       root sleep \$((\`od -vAn -N2 -tu2 < /dev/urandom\` %300)) ; /app/scripts/update-cloudflare-dns.sh" >> /etc/cron.d/cloudflare-dns && \
    echo "0        0       *       *       0       root sleep \$((\`od -vAn -N2 -tu2 < /dev/urandom\` %14400)) ; acme.sh --renew-all --config-home /app/server/files/certs/config" >> /etc/cron.d/acme-renew 

COPY --chmod=755 scripts/init-cloudflare.sh /app/scripts/
COPY --chmod=755 scripts/init-letsencrypt.sh /app/scripts/
COPY --chmod=755 scripts/update-cloudflare-dns.sh /app/scripts/
COPY --chmod=755 scripts/init-from-s3.sh /app/scripts/
COPY --chmod=755 scripts/autobackup /app/scripts/
COPY --chmod=755 scripts/autobackup-s3 /app/scripts/
COPY --chmod=755 scripts/backup-common.sh /app/scripts/

RUN chmod ugo+x /app/scripts/init-cloudflare.sh &&\
    chmod ugo+x /app/scripts/init-letsencrypt.sh &&\
    chmod ugo+x /app/scripts/update-cloudflare-dns.sh &&\
    chmod ugo+x /app/scripts/autobackup &&\
    chmod ugo+x /app/scripts/autobackup-s3 &&\
    chmod ugo+x /app/scripts/init-from-s3.sh &&\
    chmod ugo+x /app/scripts/backup-common.sh