version: '3'

services:
  mysql:
    image: mariadb:10.4
    environment:
    - MYSQL_ROOT_PASSWORD=mailtrain
    - MYSQL_DATABASE=mailtrain
    - MYSQL_USER=mailtrain
    - MYSQL_PASSWORD=mailtrain
    volumes:
    - mysql-data:/var/lib/mysql

  redis:
    image: redis:7
    volumes:
    - redis-data:/data
    deploy:
      resources:
          limits:
            cpus: "0.5"
            memory: "1G"

  mongo:
    image: mongo:6
    volumes:
    - mongo-data:/data/db
    deploy:
      resources:
          limits:
            cpus: "0.5"
            memory: "1G"

  mailtrain:
    image: mailtrain/mailtrain:latest
    ports:
    - "3000:3000"
    - "3003:3003"
    - "3004:3004"
    volumes:
    - mailtrain-files:/app/server/files
    environment:
      - URL_BASE_TRUSTED=$URL_BASE_TRUSTED
      - URL_BASE_SANDBOX=$URL_BASE_SANDBOX
      - URL_BASE_PUBLIC=$URL_BASE_PUBLIC
      - ADMIN_PASSWORD=$ADMIN_PASSWORD
      - DEFAULT_LANGUAGE=$DEFAULT_LANGUAGE
      - ENABLED_LANGUAGE=$ENABLED_LANGUAGE
      - WWW_PROXY=$WWW_PROXY
    deploy:
      resources:
          limits:
            cpus: "0.5"
            memory: "1G"

volumes:
  mysql-data:
  redis-data:
  mongo-data:
  mailtrain-files:

