'use strict';

import React, {useRef} from 'react';
import PropTypes from 'prop-types';
import {useTranslation} from '../lib/i18n';
import {Title} from '../lib/page';
import {Button, ButtonRow, Form, FormSendMethod, TableSelect} from '../lib/form';
import {Table} from '../lib/table';
import {HTTPMethod} from '../lib/axios';
import mailtrainConfig from 'mailtrainConfig';
import {useTableActionDialog} from "../lib/modals";
import {useRequiresAuthenticatedUser} from '../lib/hooks/useRequiresAuthenticatedUser';
import {useForm} from '../lib/hooks/useForm';

export default function Share({ title, entity, entityTypeId }) {
    const { t } = useTranslation();
    useRequiresAuthenticatedUser();

    const sharesTableRef = useRef(null);
    const usersTableSelectRef = useRef(null);
    const { addRestActionButton, renderDialog } = useTableActionDialog(sharesTableRef);

    const stateOwner = useForm({
        leaveConfirmation: false,
        localValidateFormValues: (state) => {
            if (!state.getIn(['userId', 'value'])) {
                state.setIn(['userId', 'error'], t('userMustNotBeEmpty'));
            } else {
                state.setIn(['userId', 'error'], null);
            }

            if (!state.getIn(['role', 'value'])) {
                state.setIn(['role', 'error'], t('roleMustBeSelected'));
            } else {
                state.setIn(['role', 'error'], null);
            }
        }
    });

    React.useEffect(() => {
        stateOwner.populateFormValues({
            entityTypeId,
            entityId: entity.id,
            userId: null,
            role: null
        });
    }, []);

    async function submitHandler() {
        stateOwner.disableForm();
        stateOwner.setFormStatusMessage('info', t('saving'));

        const submitSuccessful = await stateOwner.validateAndSendFormValuesToURL(FormSendMethod.PUT, 'rest/shares');

        if (submitSuccessful) {
            stateOwner.hideFormValidation();
            stateOwner.populateFormValues({
                entityTypeId,
                entityId: entity.id,
                userId: null,
                role: null
            });
            stateOwner.enableForm();
            stateOwner.clearFormStatusMessage();
            sharesTableRef.current && sharesTableRef.current.refresh();
            usersTableSelectRef.current && usersTableSelectRef.current.refresh();
        } else {
            stateOwner.enableForm();
            stateOwner.setFormStatusMessage('warning', t('thereAreErrorsInTheFormPleaseFixThemAnd-1'));
        }
    }

    const sharesColumns = [];
    sharesColumns.push({ data: 0, title: t('username') });
    if (mailtrainConfig.isAuthMethodLocal) {
        sharesColumns.push({ data: 1, title: t('name') });
    }
    sharesColumns.push({ data: 2, title: t('role') });

    sharesColumns.push({
        actions: data => {
            const actions = [];
            const autoGenerated = data[4];
            const userId = data[3];

            if (!autoGenerated && mailtrainConfig.user.id !== userId) {
                const username = data[0];

                addRestActionButton(
                    actions,
                    {
                        method: HTTPMethod.PUT,
                        url: 'rest/shares',
                        data: {
                            entityTypeId,
                            entityId: entity.id,
                            userId
                        },
                        refreshTables: () => {
                            sharesTableRef.current && sharesTableRef.current.refresh();
                            usersTableSelectRef.current && usersTableSelectRef.current.refresh();
                        }
                    },
                    { icon: 'trash-alt', label: t('unshare') },
                    t('confirmUnsharing'),
                    t('areYouSureYouWantToRemoveTheShareToUser', {username}),
                    t('removingShareForUserUsername', {username}),
                    t('shareForUserUsernameRemoved', {username}),
                    null
                );
            }

            return actions;
        }
    });

    let usersLabelIndex = 1;
    const usersColumns = [
        { data: 1, title: "Username" },
    ];

    if (mailtrainConfig.isAuthMethodLocal) {
        usersColumns.push({ data: 2, title: "Full Name" });
        usersLabelIndex = 2;
    }

    const rolesColumns = [
        { data: 1, title: "Name" },
        { data: 2, title: "Description" },
    ];

    return (
        <div>
            {renderDialog()}
            <Title>{title}</Title>

            <h3 className="legend">{t('addUser')}</h3>
            <Form stateOwner={stateOwner} onSubmitAsync={submitHandler}>
                <TableSelect ref={usersTableSelectRef} id="userId" label={t('user')} withHeader dropdown dataUrl={`rest/shares-unassigned-users-table/${entityTypeId}/${entity.id}`} columns={usersColumns} selectionLabelIndex={usersLabelIndex}/>
                <TableSelect id="role" label={t('role')} withHeader dropdown dataUrl={`rest/shares-roles-table/${entityTypeId}`} columns={rolesColumns} selectionLabelIndex={1}/>

                <ButtonRow>
                    <Button type="submit" className="btn-primary" icon="check" label={t('share')}/>
                </ButtonRow>
            </Form>

            <hr/>
            <h3 className="legend">{t('existingUsers')}</h3>

            <Table ref={sharesTableRef} withHeader dataUrl={`rest/shares-table-by-entity/${entityTypeId}/${entity.id}`} columns={sharesColumns} />
        </div>
    );
}

Share.propTypes = {
    title: PropTypes.string,
    entity: PropTypes.object,
    entityTypeId: PropTypes.string
};
