'use strict';

import React, {useRef} from 'react';
import PropTypes from 'prop-types';
import {useTranslation} from '../lib/i18n';
import {Title} from '../lib/page';
import {Table} from '../lib/table';
import {HTTPMethod} from '../lib/axios';
import {useTableActionDialog} from "../lib/modals";
import {useRequiresAuthenticatedUser} from '../lib/hooks/useRequiresAuthenticatedUser';

export default function UserShares({ user }) {
    const { t } = useTranslation();
    useRequiresAuthenticatedUser();

    const sharesTablesRef = useRef({});
    const firstTableRef = useRef(null);
    const { addRestActionButton, renderDialog } = useTableActionDialog(firstTableRef);

    function renderSharesTable(entityTypeId, title, typeName) {
        const columns = [
            { data: 0, title: t('name') },
            { data: 1, title: t('role') },
            {
                actions: data => {
                    const actions = [];
                    const autoGenerated = data[3];
                    const perms = data[4];

                    if (!autoGenerated && perms.includes('share')) {
                        const name = data[0];
                        const entityId = data[2];

                        addRestActionButton(
                            actions,
                            {
                                method: HTTPMethod.PUT,
                                url: 'rest/shares',
                                data: {
                                    entityTypeId,
                                    entityId,
                                    userId: user.id
                                },
                                refreshTables: () => {
                                    for (const key in sharesTablesRef.current) {
                                        sharesTablesRef.current[key] && sharesTablesRef.current[key].refresh();
                                    }
                                }
                            },
                            { icon: 'trash-alt', label: t('unshare') },
                            t('confirmUnsharing'),
                            t('areYouSureYouWantToRemoveTheSharingOfThe', {typeName, name}),
                            t('removingSharingOfTheTypeNameName', {typeName, name}),
                            t('sharingOfTheTypeNameNameRemoved', {typeName, name}),
                            null
                        );
                    }

                    return actions;
                }
            }
        ];

        return (
            <div>
                <h3>{title}</h3>
                <Table ref={node => { sharesTablesRef.current[entityTypeId] = node; if (entityTypeId === 'namespace') firstTableRef.current = node; }} withHeader dataUrl={`rest/shares-table-by-user/${entityTypeId}/${user.id}`} columns={columns} />
            </div>
        );
    }

    return (
        <div>
            {renderDialog()}
            <Title>{t('sharesForUserUsername', {username: user.username})}</Title>

            {renderSharesTable('namespace', t('namespaces'), t('namespace-1'))}
            {renderSharesTable('list', t('lists'), t('list-1'))}
            {renderSharesTable('template', t('templates'), t('template-1'))}
            {renderSharesTable('mosaicoTemplate', t('mosaicoTemplates'), t('mosaicoTemplate'))}
            {renderSharesTable('campaign', t('campaigns'), t('campaign-1'))}
            {renderSharesTable('customForm', t('customForms-1', t('customForms-2')))}
            {renderSharesTable('report', t('reports'), t('report-1'))}
            {renderSharesTable('reportTemplate', t('reportTemplates'), t('reportTemplate-2'))}
            {renderSharesTable('sendConfiguration', t('sendConfigurations-1'), t('sendConfiguration'))}
        </div>
    );
}

UserShares.propTypes = {
    user: PropTypes.object
};
