#!/bin/bash
#1-store
cd $PROJECT_ROOT
if [ -z "${CRYPTOKEN}" ]; then
    echo "CRYPTOKEN is empty: $CRYPTOKEN"
    exit -1
fi
cd $PROJECT_ROOT
tar -cvJf _sensitive_datas/_sensitive_datas.tar.xz Tiltfile private .vscode/settings.json server/config/dev.yaml k8s/okteto-kube-admb.config zone-mta/dkim.rsa devspace* dev-values.yaml
#2-encrypt
openssl aes-256-cbc -base64 -md sha256 -pass pass:"$CRYPTOKEN" -in _sensitive_datas/_sensitive_datas.tar.xz -out _sensitive_datas/_sensitive_datas.tar.xz.enc
#3-delete 
rm _sensitive_datas/_sensitive_datas.tar.xz