#!/bin/bash
MAILUSER=`cat /app/zone-mta/config/builtin-zonemta.json |sed -n 's/^.*\"user\":.*\"\(.*\)\",$/\1/p'`
MAILPASSWD=`cat /app/zone-mta/config/builtin-zonemta.json |sed -n 's/^.*\"pass\":.*\"\(.*\)\"$/\1/p'`
NOW=`date -I`
/usr/bin/mysqldump -h $MYSQL_HOST --password="$MYSQL_ROOT_PASSWORD" --all-databases | bzip2 -9 > /app/server/files/backup.sql.bz2
tar -cvjf /app/server/files/backup.tar.bz2 /app/server/files/backup.sql.bz2 /app/server/files/campaign /app/server/files/certs /app/server/files/imports /app/server/files/reports /app/server/files/template /app/server/files/uploaded
(
cat << EOF 
From: "SAUVEGARDE @HCFMailer+" <$BACKUP_FROM>
To: "Backup@Mailtrain" <$BACKUP_TO>
MIME-Version: 1.0
Subject: Sauvegarde HCFMailer+ du $NOW
Content-Type: multipart/mixed; boundary="-"

This is a MIME encoded message.  Decode it with "munpack"
or any other MIME reading software.  Mpack/munpack is available
via anonymous FTP in ftp.andrew.cmu.edu:pub/mpack/
---
Content-Type: text/plain

Voici la sauvegarde du $NOW
HCFMailer+ team

---
Content-Type: application/octet-stream; name="backup-$NOW.tar.bz2"
Content-Transfer-Encoding: base64
Content-Disposition: inline; filename="backup-$NOW.tar.bz2"

EOF
)    | (cat - && /usr/bin/openssl base64 < /app/server/files/backup.tar.bz2 && echo "" && echo "---")\
     | /usr/sbin/sendmail -f $BACKUP_FROM -au$MAILUSER -ap$MAILPASSWD -amPLAIN  -S 127.0.0.1:2525 -t --
