---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mailtrain-files
  name: mailtrain-files
spec:
  accessModes: {{ .Values.storage.main.accessModes | toYaml | nindent 4 }}
  {{ if .Values.storage.main.storageClassName }}
  storageClassName: {{ .Values.storage.main.storageClassName }}
  {{ end }}
  resources:
    requests:
      storage: {{ .Values.storage.main.size }}
  volumeMode: Filesystem
status: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mailtrain-mysql
  name: mailtrain-mysql
spec:
  accessModes: {{ .Values.storage.mysql.accessModes | toYaml | nindent 4 }}
  {{ if .Values.storage.mysql.storageClassName }}
  storageClassName: {{ .Values.storage.mysql.storageClassName }}
  {{ end }}
  resources:
    requests:
      storage: {{ .Values.storage.mysql.size }}
  volumeMode: Filesystem
status: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mailtrain-kvdata
  name: mailtrain-kvdata
spec:
  accessModes: {{ .Values.storage.kvdata.accessModes | toYaml | nindent 4 }}
  {{ if .Values.storage.kvdata.storageClassName }}
  storageClassName: {{ .Values.storage.kvdata.storageClassName }}
  {{ end }}
  resources:
    requests:
      storage: {{ .Values.storage.kvdata.size }}
  volumeMode: Filesystem
status: {}

{{ if not .Values.storage.kvdata.shareKvStorage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mailtrain-mongo
  name: mailtrain-mongo
spec:
  accessModes: {{ .Values.storage.kvdata.accessModes | toYaml | nindent 4 }}
  {{ if .Values.storage.kvdata.storageClassName }}
  storageClassName: {{ .Values.storage.kvdata.storageClassName }}
  {{ end }}
  resources:
    requests:
      storage: {{ .Values.storage.kvdata.size }}
  volumeMode: Filesystem
status: {}
{{ end }}